name: Next.js Build & Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Dependencies Install
        run: npm install

      - name: Opt-Out Telemetry
        run: npx next telemetry disable

      - name: Build
        run: npm run build

      - name: Export
        run: npm run export

      - name: Generate .nojekyll
        run: touch out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: out
          git-config-name: Build-Deploy Bot
          git-config-email: <>
          commit-message: Generated by Next.js Build & Deploy
